spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PhucVietNguyen/mor-space-config.git
          search-paths: '{application}'
          username: PhucVietNguyen
          password: '@nhphuc1996'
          default-label: "main"
  security:
    user:
      name: root
      password: 1234
server:
  port: 8888